### ISSUE TITLE
Confusing about flexible docking test.

### ISSUE THREAD

**Issue by Ming-Qin-tech** [Graylab/GeoDock#13]
To test the flexible docking performance, like DB5.5, you take unbound structure as input and bound state structures as ground truth(Label)?   But, A problem confusing me is in some cases, although sharing the same pdbid name, the protein sequence (even the length)  in pdb file of the bound state is slightly different with unbound state pdb file. So how do you deal with it?

I see the source code:
elif dataset == 'db5_test_unbound':
            self.data_dir = "/home/lchu11/scr4_jgray21/lchu11/data/pt/db5_unbound_flexible"
            self.data_list = "/home/lchu11/scr4_jgray21/lchu11/data/db5/test_unbound.txt"
            with open(self.data_list, 'r') as f:
                lines = f.readlines()
            self.file_list = [line.strip() for line in lines] 
 However, I didn't find these folders like "/pt/db5_unbound_flexible" and thus it is difficult to understand what you have done to evaluate the flexible docking performance. 
 
 Could you please give me some instructions? I would greatly appreciate it！

**Comment by Ming-Qin-tech** [comment]
For example, If I extract the protein sequence from "1a2k_r_u.pdb",  the chain A's sequence is :
"GDKPIWEQIGSSFIQHYYQLFDNDRTQLGAIYIDASCLTWEGQQFQGKAAIVEKLSSLPFQKIQHSITAQDHQPTPDSCIISMVVGQLKADEDPIMGFHQMFLLKNINDAWVCTNDMFRLALHNF"

However, the sequence from "1a2k_r_b.pdb" is :
"KPIWEQIGSSFIQHYYQLFDNDRTQLGAIYIDASCLTWEGQQFQGKAAIVEKLSSLPFQKIQHSITAQDHQPTPDSCIISMVVGQLKADEDPIMGFHQMFLLKNINDAWVCTNDMFRLALHNFG"

we can see the different of the sequence length, and it is unacceptable to DockQ calculate(need same length). So How do you deal with it?

**Comment by lchu11** [comment]
Hi, we preprocessed the pdbs to make sure the chains in bound and unbound are consistent. 

For example:
In 1a2k_r_u.pdb, we deleted "GD" at the beginning:
"~~GD~~KPIWEQIGSSFIQHYYQLFDNDRTQLGAIYIDASCLTWEGQQFQGKAAIVEKLSSLPFQKIQHSITAQDHQPTPDSCIISMVVGQLKADEDPIMGFHQMFLLKNINDAWVCTNDMFRLALHNF"
And in 1a2k_r_b.pdb, we deleted "G" at the end:
"KPIWEQIGSSFIQHYYQLFDNDRTQLGAIYIDASCLTWEGQQFQGKAAIVEKLSSLPFQKIQHSITAQDHQPTPDSCIISMVVGQLKADEDPIMGFHQMFLLKNINDAWVCTNDMFRLALHNF~~G~~"
