### ISSUE TITLE
specify the location of the esm model

### ISSUE THREAD

**Issue by celalp** [Graylab/GeoDock#14]
Hi thanks for your hard work. I am interested in running this tool in a shared hpc environment and I would like to be able to specify the location of the ESM model (we also have some in house fine-tuned ones as well). In the current code I do not see a way to do this and when not present the model get downloaded to ~/.cache. 

Is there a way to point the GeoDockRunner to an already downloaded ESM checkpoint?

Thanks again

**Comment by lchu11** [comment]
Yes, you can simply change the line 20 in GeoDockRunner.py 
from `self.esm_model, alphabet = esm.pretrained.esm2_t33_650M_UR50D()`
to `self.esm_model, alphabet = esm.pretrained.load_model_and_alphabet('path to your .ckpt')`
