### ISSUE TITLE
Possible to split to run on multiple CPUs/GPUs? 

### ISSUE THREAD

**Issue by hthorpe31** [Graylab/GeoDock#3]
Hi all,

Similar to another issue listed, I also tried to run a .pdb and ran out of memory on our server's a100 80GB GPU. I'm not sure if some of the operations need to be done on the CPU, but either way I was wondering if it is possible to change the python script to use multiple GPUs/CPUs to run the script on, since changing my batch header to multiple GPUs it still only ran on one, and how that change would be implemented.

Thanks.

**Comment by Tsuchihashi-ryo** [comment]
Hi, I had the same problem.
My solution was to send a part of the model to another GPU (GPU:1) and send the tensor computed on GPU:0 to GPU:1 and then back to GPU:0 again after computation.
The biggest place in this network is the graph module, so I put part of it (blocks 0 and 1 except 2) in GPU:1.

```python
# Load GeoDock model to GPU:0
model = GeoDock.load_from_checkpoint(ckpt_file,
                                      map_location="cuda:0"
                                     ).eval().to("cuda:0")

# Send part of the model to GPU:1
model.net.graph_module.blocks[0] = model.net.graph_module.blocks[0].to("cuda:1")
model.net.graph_module.blocks[1] = model.net.graph_module.blocks[1].to("cuda:1")
```

Also, in this case, the GraphModule in geodock/model/modules/graph_module.py needs to be rewritten.

```python
class GraphModule(nn.Module):
    def __init__(
        self,
        *,
        node_dim, 
        edge_dim,
        depth,
    ):
        super().__init__()
        self.blocks = nn.ModuleList([])
        for _ in range(depth):
            self.blocks.append(GraphBlock(node_dim=node_dim, edge_dim=edge_dim))

    def forward(self, node, edge):
        # Send tensor to GPU:1
        node = node.to("cuda:1")
        edge = edge.to("cuda:1")
　　
        node, edge = self.block[0](node, edge)
        node, edge = self.block[1](node, edge)  

        # Return tensor to GPU:0
        node = node.to("cuda:0")
        edge = edge.to("cuda:0")       
        
        for block in self.blocks[2:]:            
            node, edge = block(node, edge)

        return node, edge
```
I hope this helps.

**Comment by hthorpe31** [comment]
Thank you! It does in two ways - I was close to coming up with the node.to and edge.to solution, but wasn't 100% sure how to implement it (and only got there after hours of searching through Google and PyTorch documentation), so it was nice to know I was on the right track, and it also helps to see that it needed some code elsewhere for it to ultimately work, because I didn't know that at all.

That said, I am wondering where the first chunk of code would go. I assumed it was in line 25 in GeoDockRunner.py, which currently has 
`
self.model = GeoDock.load_from_checkpoint(ckpt_file, map_location=self.device).eval().to(self.device)`

but when I replaced it with what you have I got an error that
`
AttributeError: 'GeoDockRunner' object has no attribute 'model'`

My other guess is that it might replace line 168 in GeoDock.py, but then wasn't sure if when it was called in GeoDockRunner.py in the line I posted above it would override it and go back to one GPU.

So sorry for not knowing, but where would that first chunk of code you wrote go into? Thanks.

**Comment by Tsuchihashi-ryo** [comment]
My apologies for the lack of explanation.
I was running the code in notebook without GeoDockRunner, so it may have thrown an error. Would it work if I create a child class as follows?

```python
import esm
import torch
from time import time
from geodock.utils.embed import embed
from geodock.utils.docking import dock
from geodock.model.GeoDock import GeoDock
from esm.inverse_folding.util import load_coords
from geodock.GeoDockRunner import GeoDockRunner


class GeoDockRunner_multiGPU(GeoDockRunner):
    def __init__(self, ckpt_file):

        # Load GeoDock model to GPU:0
        self.device = "cuda:0"
        #self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Load ESM-2 model
        self.esm_model, alphabet = esm.pretrained.esm2_t33_650M_UR50D()
        self.batch_converter = alphabet.get_batch_converter()
        self.esm_model.eval().to(self.device)  # disables dropout for deterministic results

        # Load GeoDock model
        self.model = GeoDock.load_from_checkpoint(ckpt_file, map_location=self.device).eval().to(self.device)

        # Send part of the model to GPU:1
        self.model.net.graph_module.blocks[0] = self.model.net.graph_module.blocks[0].to("cuda:1")
        self.model.net.graph_module.blocks[1] = self.model.net.graph_module.blocks[1].to("cuda:1")


geodock = GeoDockRunner_multiGPU(ckpt_file=ckpt_file)
  pred = geodock.dock(
      partner1=partner1, 
      partner2=partner2,
      out_name=out_name,
      do_refine=Flase,
      use_openmm=True,
  )

**Comment by rubenalv** [comment]
Hi, small correction in case someone else comes across this post:
Instead of
```
        node, edge = self.block[0](node, edge)
        node, edge = self.block[1](node, edge) 
```
it should be
```
        node, edge = self.blocks[0](node, edge) # blockS, because self.block does not exist
        node, edge = self.blocks[1](node, edge) # blockS
```
Also I put the class GeoDockRunner_multiGPU within GeoDockRunner.py.

Thank you so much @Tsuchihashi-ryo (and @hthorpe31), it does make a difference to be able to run this in 2 GPUs!
