### ISSUE TITLE
Try to retrain the model, but missing 'rigid_ Docking. datasets. dips_ Datamodule DipsDataModule'.

### ISSUE THREAD

**Issue by jkwang93** [Graylab/GeoDock#4]
This is a very cool job! thank you to provide the code. However, when I tried to reproduce, I encountered the following problem, missing these 'rigid_ docking 'and training dataset:

_target_: rigid_docking.datasets.dips_datamodule.DipsDataModule

data_dir: /home/lchu11/scr4_jgray21/lchu11/Docking-dev/data/dips/pt_files
train_list: /home/lchu11/scr4_jgray21/lchu11/Docking-dev/data/dips_equidock/train_list_rev.txt
val_list: /home/lchu11/scr4_jgray21/lchu11/Docking-dev/data/dips_equidock/val_list_rev.txt
test_list: /home/lchu11/scr4_jgray21/lchu11/Docking-dev/data/dips_equidock/test_list.txt
batch_size: 1
num_workers: 6
pin_memory: True

**Comment by lchu11** [comment]
Hi @jkwang93,

Sorry for the confusion. The data can be downloaded from [DIPS](https://www.dropbox.com/s/sqknqofy58nlosh/DIPS.zip?dl=0) or follow the steps stated in the [EquiDock repo](https://github.com/octavian-ganea/equidock_public#dips-data).

**Comment by jkwang93** [comment]
Thank you very much for your answer. According to your answer, I downloaded DIPS data and your brand new code. But I still encountered problems while training. 

The data downloaded by DIPS is  **'.dill'** format, but your input for training is **'.pt'** .Then I found the gen_dataset.py that generates the .pt file, but this script need to input the **'.pdb'** file. But the DIPS data I downloaded is **'.dill'** format. 

May I ask if the code provided complete?

In addition, I also saw the data path of DIPS_alphafold. Can you provide this part of the data?

**Comment by lchu11** [comment]
sorry for late response. Just uploaded the preprocess code on https://github.com/Graylab/GeoDock/blob/main/geodock/datasets/gen_dips_dataset.py
