### ISSUE TITLE
Complex from colab notebook different from structure generated using my own notebook 

### ISSUE THREAD

**Issue by susiegriggo** [Graylab/GeoDock#5]
Thanks for developing this software! The colab notebook has been very fast and easy to use. 

I have two proteins which I have been trying to dock using GeoDock. If I use the Colab notebook I've noticed that I get a much better looking complex compared to when I've cloned the repo and used the the GeoDockRunner module in my own notebook. 

For reference, when I dock two proteins using the colab notebook  I get a complex that seems quite reasonable: 

![image](https://github.com/Graylab/GeoDock/assets/54240311/11962b9e-82df-4b5f-a045-51e007c8564a)

However, when I take these same two structures in my own notebook, this is complex I get (visualised using chimeraX): 

![image](https://github.com/Graylab/GeoDock/assets/54240311/f653d810-5db3-45fd-997f-0bd65e8edc54)

which seems a little odd. 

This  is the code that I ran in my own notebook

```
import sys
import torch
from geodock.GeoDockRunner import GeoDockRunner

torch.cuda.empty_cache()
ckpt_file = "geodock/weights/dips.ckpt"
geodock = GeoDockRunner(ckpt_file=ckpt_file)

pred = geodock.dock(
    partner1='E_esmfold2.pdb',
    partner2='D_esmfold2.pdb',
    out_name='test',
    do_refine=False,
    use_openmm=True,
)
```

The only thing I can think of is perhaps that I am running my notebook using CPU only? Obviously this would explain why it takes longer but I thought this shouldn't have effected the docking. Is there a way I could replicate the structures I get using the colab notebook locally?  

In case it is relevant this is what I am using (can give more if needed). 
* cudatoolkit=11.8.0 
* pytorch=2.1.0 
* python=3.9 

I've attached the two protein structures and the unusual complex I generate for reference. 
[geodock_issue.zip](https://github.com/Graylab/GeoDock/files/12821858/geodock_issue.zip)

Thanks!

**Comment by lchu11** [comment]
Hi @susiegriggo,

Thanks for pointing out the issue. The inconsistency was due to the different versions of the model on Pypi and GitHub. I have published the updated version so the problem should now be fixed. Let me know if you still have the problem after re-cloning the repo and running the GeoDockRunner.py.
